services:
  postgres:
    image: postgres:latest
    container_name: localpostgresdb
    environment:
      POSTGRES_USER: soumyadip
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
